### ISSUE TITLE
ModuleNotFoundError Import error in display.py: No module named 'board'

### ISSUE THREAD

**Issue by jimratliff** [ahira-justice/chess-board#6]
I'm getting the following error:
```
Python 3.9.13 (main, May 24 2022, 21:13:51)
[Clang 13.1.6 (clang-1316.0.21.2)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from chessboard import display
pygame 2.1.2 (SDL 2.0.18, Python 3.9.13)
Hello from the pygame community. https://www.pygame.org/contribute.html
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/path/to/venv/lib/python3.9/site-packages/chessboard/display.py", line 7, in <module>
    from board import Board, Color
ModuleNotFoundError: No module named 'board'
```

To clarify versions, etc., here’s my `pip list`:
```
Package     Version
----------- -------
build       0.8.0
chess-board 0.3.0
packaging   21.3
pep517      0.12.0
pip         22.1.2
pygame      2.1.2
pyparsing   3.0.9
setuptools  63.1.0
tomli       2.0.1
```

**Comment by ahira-justice** [comment]
Hello @jimratliff,

I have fixed this error in the latest release, v0.3.1
